apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-portal-sa
  namespace: hsps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: security-portal-role
  namespace: hsps
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: security-portal-rolebinding
  namespace: hsps
subjects:
- kind: ServiceAccount
  name: security-portal-sa
  namespace: hsps
roleRef:
  kind: Role
  name: security-portal-role
  apiGroup: rbac.authorization.k8s.io
