apiVersion: v1
kind: Service
metadata:
  name: hsps-webui-simulator
  namespace: hsps
  labels:
    app: hsps-webui-simulator
    component: webui
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: hsps-webui-simulator
