apiVersion: v1
kind: ConfigMap
metadata:
  name: star-config
  namespace: star
data:
  SECURITY_PORTAL_URL: "http://security-portal.star.svc.cluster.local:8000"
  anomaly_frequency: "0.15"
  log_level: "INFO"
