apiVersion: v1
kind: ServiceAccount
metadata:
  name: star-database-sa
  namespace: star
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: star-database-role
  namespace: star
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: star-database-rolebinding
  namespace: star
subjects:
- kind: ServiceAccount
  name: star-database-sa
  namespace: star
roleRef:
  kind: Role
  name: hsps-database-role
  apiGroup: rbac.authorization.k8s.io
